_target_: src.models.sa_eend_module.SAEENDModule
infer_dir: ${original_work_dir}/infer/${name}
lr: !!float 1.0
optimizer: noam
noam_warmup_steps: 100000
gradient_accumulation_steps: 1
gradclip: 5
chunk_size: 500

net:
  _target_: src.models.components.sa_eend_spk_embed.SAEENDSpkEmbed
  n_speakers: 2
  in_size: 345
  n_heads: 4
  n_units: 256
  n_layers: 4
  dim_feedforward: 2048
  dropout: 0.1
  has_pos: False
  spk_emb_dim: 256
