_target_: src.models.sa_eend_module.SAEENDModule
lr: 1e-3
weight_decay: 0.0005

net:
  _target_: src.models.components.sa_eend.SAEEND
  n_speakers: 2
  in_size: 345
  n_heads: 4
  n_units: 256
  n_layers: 4
  dim_feedforward: 2048
  dropout: 0.1
  has_pos: False
